apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.operator.metalbear.co
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
spec:
  group: operator.metalbear.co
  groupPriorityMinimum: 1000
  insecureSkipTLSVerify: {{ .Values.tls.apiService.insecureSkipTLSVerify }}
  service:
    name: {{ .Values.service.name }}
    namespace: {{ .Values.namespace }}
    port: {{ .Values.operator.port }}
  version: v1
  versionPriority: 15
