apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ''
  - apps
  - batch
  - argoproj.io
  resources:
  - nodes
  - pods
  - pods/log
  - pods/ephemeralcontainers
  - deployments
  - deployments/scale
  - rollouts
  - rollouts/scale
  - jobs
  - cronjobs
  - statefulsets
  - statefulsets/scale
  - services
  - replicasets
  verbs:
  - get
  - list
  - watch
# For patching target workloads: scale down for copy target and env injection for queue splitting.
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  verbs:
  - patch
- apiGroups:
  - ""
  - batch
  resources:
  - jobs
  - pods
  verbs:
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - pods/ephemeralcontainers
  verbs:
  - update
- apiGroups:
  - apps
  - argoproj.io
  resources:
  - deployments/scale
  - rollouts/scale
  - statefulsets/scale
  verbs:
  - patch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - policies.mirrord.metalbear.co
  resources:
  - mirrordpolicies
  - mirrordclusterpolicies
  verbs:
  - list
  - get
  - watch
{{- if .Values.operator.sqsSplitting }}
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordworkloadqueueregistries
  verbs:
  - list
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordworkloadqueueregistries/status
  verbs:
  - update
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordsqssessions
  verbs:
  - create
  - watch
  - list
  - get
  - delete
  - deletecollection
  - patch
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordsqssessions/status
  verbs:
  - update
{{- if .Values.operator.mutatingWebhooks }}
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - mutatingwebhookconfigurations
  verbs:
    - get
    - delete
    - deletecollection
{{- end }}
{{- end }}
{{- if .Values.operator.kafkaSplitting }}
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordkafkaephemeraltopics
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordkafkaclientconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordkafkatopicsconsumers
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- if .Values.operator.applicationPauseAutoSync }}
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - list
  - get
  - patch
{{- end }}
- apiGroups:
  - mirrord.metalbear.co
  resources:
  - mirrordtlsstealconfigs
  - mirrordclustertlsstealconfigs
  verbs:
  - list
  - get
- apiGroups:
  - ''
  resources:
  - podtemplates
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator-user
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
    {{- if index .Values.clusterRole "mirrord-operator-user" "labels" }}
          {{- toYaml (index .Values.clusterRole "mirrord-operator-user" "labels") | nindent 4 }}
    {{- end }}
rules:
{{- include "mirrord-operator.rules" . | nindent 0 }}
{{- include "mirrord-operator.clusterRules" . | nindent 0 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator-user-basic
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
    {{- if index .Values.clusterRole "mirrord-operator-user-basic" "labels" }}
          {{- toYaml (index .Values.clusterRole "mirrord-operator-user-basic" "labels") | nindent 4 }}
    {{- end }}
rules:
{{- include "mirrord-operator.clusterRules" . | nindent 0 }}
