apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ''
  - apps
  - batch
  - argoproj.io
  resources:
  - nodes
  - pods
  - pods/log
  - pods/ephemeralcontainers
  - deployments
  - deployments/scale
  - rollouts
  - rollouts/scale
  - jobs
  - cronjobs
  - statefulsets
  - statefulsets/scale
  - services
  - replicasets
  verbs:
  - get
  - list
  - watch
# For patching and unpatching target workloads: scale down for copy target and env injection for queue splitting.
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  verbs:
  - patch
- apiGroups:
  - ""
  - batch
  resources:
  - jobs
  - pods
  verbs:
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - pods/ephemeralcontainers
  verbs:
  - update
- apiGroups:
  - apps
  - argoproj.io
  resources:
  - deployments/scale
  - rollouts/scale
  - statefulsets/scale
  verbs:
  - patch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - policies.mirrord.metalbear.co
  resources:
  - mirrordpolicies
  - mirrordclusterpolicies
  verbs:
  - list
  - get
  - watch
{{- if .Values.operator.sqsSplitting }}
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordworkloadqueueregistries
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordworkloadqueueregistries/status
  verbs:
  - update
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordsqssessions
  verbs:
  - create
  - watch
  - list
  - get
  - delete
  - deletecollection
  - patch
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordsqssessions/status
  verbs:
  - update
{{- end }}
# For deleting previously mutated pods
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - deletecollection
# For fetching the operator cluster role.
# The role is used as an owner reference
# for various native resources created by the operator.
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles
  resourceNames:
    - mirrord-operator
  verbs:
    - get
# For creating and managing mutating webhook configs.
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - mutatingwebhookconfigurations
  verbs:
    - create
    - get
    - update
    - patch
    - delete
    - deletecollection
    - list
{{- if .Values.operator.kafkaSplitting }}
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordkafkaephemeraltopics
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordkafkaclientconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - queues.mirrord.metalbear.co
  resources:
  - mirrordkafkatopicsconsumers
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- if or .Values.operator.sqsSplitting .Values.operator.kafkaSplitting }}
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- if .Values.operator.applicationPauseAutoSync }}
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - list
  - get
  - patch
{{- end }}
- apiGroups:
  - mirrord.metalbear.co
  resources:
  - mirrordtlsstealconfigs
  - mirrordclustertlsstealconfigs
  verbs:
  - list
  - get
- apiGroups:
  - ''
  resources:
  - podtemplates
  verbs:
  - list
  - get
  - watch
{{- if .Values.operator.isolatePodsRestart }}
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - patch
{{- end }}
{{- if .Values.operator.mysqlBranching }}
- apiGroups:
  - dbs.mirrord.metalbear.co
  resources:
  - mysqlbranchdatabases
  verbs:
  - list
  - get
  - watch
  - delete
  - update
  - patch
- apiGroups:
  - dbs.mirrord.metalbear.co
  resources:
  - mysqlbranchdatabases/status
  verbs:
  - get
  - update
  - patch
{{- end }}
{{- if .Values.operator.pgBranching }}
- apiGroups:
  - dbs.mirrord.metalbear.co
  resources:
  - pgbranchdatabases
  verbs:
  - list
  - get
  - watch
  - delete
  - update
  - patch
- apiGroups:
  - dbs.mirrord.metalbear.co
  resources:
  - pgbranchdatabases/status
  verbs:
  - get
  - update
  - patch
{{- end }}
{{- if .Values.operator.multiCluster.enabled }}
# For multi-cluster sessions (Envoy)
- apiGroups:
  - operator.metalbear.co
  resources:
  - mirrordmulticlustersessions
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - operator.metalbear.co
  resources:
  - mirrordmulticlustersessions/status
  verbs:
  - get
  - update
  - patch
{{- end }}
# For private cluster sessions (Private Interface - runs on all clusters)
- apiGroups:
  - operator.metalbear.co
  resources:
  - mirrordprivateclustersessions
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - operator.metalbear.co
  resources:
  - mirrordprivateclustersessions/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - mirrord.metalbear.co
  resources:
  - mirrordclusterworkloadpatches
  - mirrordclusterworkloadpatchrequests
  - mirrordclusterworkloadpatchrequests/status
  - mirrordclustersessions
  - mirrordclustersessions/status
  - mirrordclusterexternalresources
  verbs:
  - list
  - get
  - watch
  - delete
  - deletecollection
  - update
  - patch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator-user
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
    {{- if index .Values.clusterRole "mirrord-operator-user" "labels" }}
          {{- toYaml (index .Values.clusterRole "mirrord-operator-user" "labels") | nindent 4 }}
    {{- end }}
rules:
{{- include "mirrord-operator.rules" . | nindent 0 }}
{{- include "mirrord-operator.clusterRules" . | nindent 0 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator-user-basic
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
    {{- if index .Values.clusterRole "mirrord-operator-user-basic" "labels" }}
          {{- toYaml (index .Values.clusterRole "mirrord-operator-user-basic" "labels") | nindent 4 }}
    {{- end }}
rules:
{{- include "mirrord-operator.clusterRules" . | nindent 0 }}
