apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ''
  - apps
  - batch
  - argoproj.io
  resources:
  - nodes
  - pods
  - pods/log
  - pods/ephemeralcontainers
  - deployments
  - deployments/scale
  - rollouts
  - rollouts/scale
  - jobs
  - cronjobs
  - statefulsets
  - statefulsets/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  verbs:
  - patch
- apiGroups:
  - ""
  - batch
  resources:
  - jobs
  - pods
  verbs:
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - pods/ephemeralcontainers
  verbs:
  - update
- apiGroups:
  - apps
  - argoproj.io
  resources:
  - deployments/scale
  - rollouts/scale
  - statefulsets/scale
  verbs:
  - patch
- apiGroups:
  - ''
  - authentication.k8s.io
  resources:
  - groups
  - users
  - userextras/accesskeyid
  - userextras/arn
  - userextras/canonicalarn
  - userextras/sessionname
  - userextras/iam.gke.io/user-assertion
  - userextras/user-assertion.cloud.google.com
  - userextras/principalid
  - userextras/oid
  - userextras/username
  - userextras/licensekey
  verbs:
  - impersonate
- apiGroups:
  - policies.mirrord.metalbear.co
  resources:
  - mirrordpolicies
  verbs:
  - list
  - get
- apiGroups:
  - splitters.mirrord.metalbear.co
  resources:
  - mirrordqueuesplitters
  verbs:
  - list
- apiGroups:
  - splitters.mirrord.metalbear.co
  resources:
  - mirrordqueuesplitters/status
  verbs:
  - update
- apiGroups:
  - splitters.mirrord.metalbear.co
  resources:
  - mirrordsqssessions
  verbs:
  - create
  - watch
  - list
  - get
  - delete
  - patch
- apiGroups:
  - splitters.mirrord.metalbear.co
  resources:
  - mirrordsqssessions/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator-user
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
rules:
{{- include "mirrord-operator.rules" . | nindent 0 }}
{{- include "mirrord-operator.clusterRules" . | nindent 0 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator-user-basic
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
rules:
{{- include "mirrord-operator.clusterRules" . | nindent 0 }}
