apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator
rules:
- apiGroups:
  - ''
  - apps
  - batch
  - argoproj.io
  resources:
  - nodes
  - pods
  - pods/log
  - pods/ephemeralcontainers
  - deployments
  - deployments/scale
  - jobs
  - rollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - pods/ephemeralcontainers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - deployments/scale
  verbs:
  - patch
- apiGroups:
  - ''
  - authentication.k8s.io
  resources:
  - groups
  - users
  - userextras/accesskeyid
  - userextras/arn
  - userextras/canonicalarn
  - userextras/sessionname
  - userextras/iam.gke.io/user-assertion
  - userextras/user-assertion.cloud.google.com
  - userextras/principalid
  - userextras/oid
  verbs:
  - impersonate
- apiGroups:
  - policies.mirrord.metalbear.co
  resources:
  - mirrordpolicies
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator-user
rules:
- apiGroups:
  - operator.metalbear.co
  resources:
  - copytargets
  - mirrordoperators
  - targets
  - targets/port-locks
  verbs:
  - get
  - list
- apiGroups:
  - operator.metalbear.co
  resources:
  - mirrordoperators/certificate
  - copytargets
  verbs:
  - create
- apiGroups:
  - operator.metalbear.co
  resources:
  - targets
  - copytargets
  verbs:
  - proxy
