apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator
  labels:
    {{- template "mirrord-operator.labels" . }}
rules:
- apiGroups:
  - ''
  - apps
  - batch
  - argoproj.io
  resources:
  - nodes
  - pods
  - pods/log
  - pods/ephemeralcontainers
  - deployments
  - deployments/scale
  - jobs
  - rollouts
  - rollouts/scale
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - batch
  resources:
  - jobs
  - pods
  verbs:
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - pods/ephemeralcontainers
  verbs:
  - update
- apiGroups:
  - apps
  - argoproj.io
  resources:
  - deployments/scale
  - rollouts/scale
  verbs:
  - patch
- apiGroups:
  - ''
  - authentication.k8s.io
  resources:
  - groups
  - users
  - userextras/accesskeyid
  - userextras/arn
  - userextras/canonicalarn
  - userextras/sessionname
  - userextras/iam.gke.io/user-assertion
  - userextras/user-assertion.cloud.google.com
  - userextras/principalid
  - userextras/oid
  verbs:
  - impersonate
- apiGroups:
  - policies.mirrord.metalbear.co
  resources:
  - mirrordpolicies
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator-user
rules:
{{- include "mirrord-operator.rules" . | nindent 0 }}
{{- include "mirrord-operator.clusterRules" . | nindent 0 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator-user-basic
rules:
{{- include "mirrord-operator.clusterRules" . | nindent 0 }}