{{- if .Values.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.tls.certManager.issuer }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
