{{- if and .Values.tls.certManager.enabled .Values.tls.certManager.createIssuer }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.tls.certManager.issuer }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.operator.annotations }}
  annotations:
    {{- include "mirrord-operator.annotations" . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
