{{- if or .Values.license.file.data .Values.license.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.license.file.secret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
stringData:
  {{- with .Values.license.file.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if .Values.license.key }}
  OPERATOR_LICENSE_KEY: {{ .Values.license.key | quote }}
  {{- end }}
{{- end }}
{{- /*
only create the secret if PEM license data was provided
*/}}
