{{- if .Values.license.file.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.license.file.secret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.license.file.data | nindent 2 }}
{{- else if .Values.license.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.license.file.secret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
stringData:
  OPERATOR_LICENSE_KEY: {{ .Values.license.key }}
  {{- if .Values.license.licenseServer }}
  OPERATOR_LICENSE_SERVER: {{ .Values.license.licenseServer }}
  {{- end }}
{{- else if .Values.license.licenseServer }}
  {{- required "licenseServer was specified without license key" .Values.license.key }}
{{- end }}
{{- /*
don't create secret if using keyRef or pemRef
*/}}