{{- if .Values.license.file.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.license.file.secret }}
  namespace: {{ .Values.namespace }}
stringData:
  {{- toYaml .Values.license.file.data | nindent 2 }}
{{- else if .Values.license.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.license.file.secret }}
  namespace: {{ .Values.namespace }}
stringData:
  OPERATOR_LICENSE_KEY: {{ .Values.license.key }}
{{- end }}
{{- /*
don't create secret if using keyRef or pemRef
*/}}