{{- if and .Values.operator.multiCluster.enabled .Values.operator.multiCluster.clusters }}
{{- range $clusterName, $clusterConfig := .Values.operator.multiCluster.clusters }}
{{- if or $clusterConfig.bearerToken $clusterConfig.clientCertData $clusterConfig.clientKeyData }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mirrord-cluster-{{ $clusterName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: mirrord-operator
    app.kubernetes.io/component: multi-cluster
    mirrord.metalbear.co/cluster-credentials: "true"
type: Opaque
stringData:
  {{- if $clusterConfig.bearerToken }}
  bearerToken: {{ $clusterConfig.bearerToken | quote }}
  {{- end }}
  {{- if $clusterConfig.clientCertData }}
  clientCertData: {{ $clusterConfig.clientCertData | quote }}
  {{- end }}
  {{- if $clusterConfig.clientKeyData }}
  clientKeyData: {{ $clusterConfig.clientKeyData | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
