{{- if and .Values.operator.multiCluster.enabled .Values.operator.multiCluster.clusters }}
{{- range $clusterName, $clusterConfig := .Values.operator.multiCluster.clusters }}
{{- if or $clusterConfig.bearerToken (and $clusterConfig.tlsCrt $clusterConfig.tlsKey) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mirrord-cluster-{{ $clusterName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    operator.metalbear.co/remote-cluster-credentials: "true"
type: Opaque
stringData:
  {{- if $clusterConfig.bearerToken }}
  bearerToken: {{ $clusterConfig.bearerToken | quote }}
  {{- end }}
  {{- if $clusterConfig.tlsCrt }}
  tls.crt: {{ $clusterConfig.tlsCrt | quote }}
  {{- end }}
  {{- if $clusterConfig.tlsKey }}
  tls.key: {{ $clusterConfig.tlsKey | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
