{{- if and .Values.operator.multiCluster.enabled .Values.operator.multiCluster.clusters }}
{{- range $clusterName, $clusterConfig := .Values.operator.multiCluster.clusters }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mirrord-cluster-{{ $clusterName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: mirrord-operator
    app.kubernetes.io/component: multi-cluster
    mirrord.metalbear.co/remote-cluster: "true"
type: Opaque
stringData:
  name: {{ $clusterName | quote }}
  server: {{ $clusterConfig.server | quote }}
  {{- if $clusterConfig.caData }}
  caData: {{ $clusterConfig.caData | quote }}
  {{- end }}
  {{- if $clusterConfig.bearerToken }}
  bearerToken: {{ $clusterConfig.bearerToken | quote }}
  {{- end }}
  {{- if $clusterConfig.clientCertData }}
  clientCertData: {{ $clusterConfig.clientCertData | quote }}
  {{- end }}
  {{- if $clusterConfig.clientKeyData }}
  clientKeyData: {{ $clusterConfig.clientKeyData | quote }}
  {{- end }}
{{- end }}
{{- end }}
