{{- range $.Values.roleNamespaces -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mirrord-operator-user
  namespace: {{.}}
  labels:
    {{- template "mirrord-operator.labels" . }}
rules:
{{- include "mirrord-operator.rules" . | nindent 0 }}
---
{{- end }}  