{{- range $.Values.roleNamespaces -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mirrord-operator-user
  namespace: {{.}}
rules:
- apiGroups:
  - operator.metalbear.co
  resources:
  - copytargets
  - targets
  - targets/port-locks
  verbs:
  - get
  - list
- apiGroups:
  - operator.metalbear.co
  resources:
  - copytargets
  verbs:
  - create
- apiGroups:
  - operator.metalbear.co
  resources:
  - targets
  - copytargets
  verbs:
  - proxy
- apiGroups:
  - operator.metalbear.co
  resources:
  - sessions
  verbs:
  - deletecollection
  - delete
---
{{- end }}  