{{- range .Values.roleNamespaces -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mirrord-operator-user
  namespace: {{.}}
  labels:
    {{- include "mirrord-operator.labels" $ | nindent 4 }}
    {{- if index $.Values.role "mirrord-operator-user" "labels" }}
          {{- toYaml (index $.Values.role "mirrord-operator-user" "labels") | nindent 4 }}
    {{- end }}
rules:
{{- include "mirrord-operator.rules" . | nindent 0 }}
---
{{- end }}  