{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  {{- if .Values.operator.annotations }}
  annotations:
    {{- include "mirrord-operator.annotations" . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
{{ end }}
