apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mirrord-operator-apiserver-authentication
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resourceNames:
  - extension-apiserver-authentication
  resources:
  - configmaps
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mirrord-operator
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
# For leader election when running multiple replicas
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
  - patch
# For patching operator pod with leader label
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - patch