apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mirrord-operator-apiserver-authentication
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mirrord-operator-apiserver-authentication
subjects:
- kind: ServiceAccount
  name: mirrord-operator
  namespace: mirrord
