{{- if .Values.openshift }}
{{- $agentNamespace := .Values.namespace }}
{{- $agentServiceAccount := "default" }}
{{- if and .Values.agent.extraConfig (kindIs "map" .Values.agent.extraConfig) }}
{{- with get .Values.agent.extraConfig "namespace" }}
{{- $agentNamespace = . }}
{{- end }}
{{- with get .Values.agent.extraConfig "service_account" }}
{{- $agentServiceAccount = . }}
{{- end }}
{{- end }}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-mirrord
  labels:
    {{- include "mirrord-operator.labels" . | nindent 4 }}
allowHostPID: true
allowPrivilegedContainer: false
allowHostDirVolumePlugin: true
allowedCapabilities: ["SYS_ADMIN", "SYS_PTRACE", "NET_RAW", "NET_ADMIN"]
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
seccompProfiles: ["*"]
users:
- system:serviceaccount:{{ .Values.namespace }}:{{ .Values.sa.name }}
- system:serviceaccount:{{ $agentNamespace }}:{{ $agentServiceAccount }}
{{ end }}
