apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: mirrord-operator
    {{- include "mirrord-operator.labels" . | nindent 4 }}
  name: {{ .Values.sa.name }}
  namespace: {{ .Values.namespace }}
