apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if or .Values.sa.roleArn .Values.sa.roleGke }}
  annotations:
    {{- if .Values.sa.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.sa.roleArn }}
    {{- end }}
    {{- if .Values.sa.roleGke }}
    iam.gke.io/gcp-service-account: {{ .Values.sa.roleGke }}
    {{- end }}
  {{- end }}
  labels:
    app: mirrord-operator
    {{- include "mirrord-operator.labels" . | nindent 4 }}
  name: {{ .Values.sa.name }}
  namespace: {{ .Values.namespace }}
