apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if or .Values.sa.roleArn .Values.sa.gcpSa }}
  annotations:
    {{- if .Values.sa.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.sa.roleArn }}
    {{- end }}
    {{- if .Values.sa.gcpSa }}
    iam.gke.io/gcp-service-account: {{ .Values.sa.gcpSa }}
    {{- end }}
  {{- end }}
  labels:
    app: mirrord-operator
    {{- include "mirrord-operator.labels" . | nindent 4 }}
  name: {{ .Values.sa.name }}
  namespace: {{ .Values.namespace }}
{{- if and .Values.operator.multiClusterMember (not .Values.operator.multiClusterMemberIamGroup) }}
---
# ServiceAccount used by the PRIMARY operator to authenticate to this cluster.
# Not needed when using IAM auth (multiClusterMemberIamGroup is set).
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mirrord-operator-envoy
  namespace: mirrord
{{- end }}
