apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.sa.roleArn or .Values.sa.roleGke }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.sa.roleArn }}
    iam.gke.io/gcp-service-account: {{ .Values.sa.roleGke }}
  {{- end }}
  labels:
    app: mirrord-operator
    {{- include "mirrord-operator.labels" . | nindent 4 }}
  name: {{ .Values.sa.name }}
  namespace: {{ .Values.namespace }}
