apiVersion: v1
kind: Service
metadata:
  labels:
    app: mirrord-operator
    {{- include "mirrord-operator.labels" . | nindent 4 }}
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.operator.port }}
    targetPort: https
  {{- if .Values.operator.temporalSplitting }}
  - name: temporal
    port: {{ .Values.operator.temporalProxy.port }}
    targetPort: temporal
  {{- end }}
  {{- if or .Values.operator.multiCluster.enabled .Values.operator.multiClusterMember }}
  - name: db-tunnel
    port: 4980
    targetPort: db-tunnel
  {{- end }}
  selector:
    app: mirrord-operator
    mirrord-operator-leader: "true"
  type: ClusterIP
