{{- if not .Values.tls.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secret }}
  namespace: {{ .Values.namespace }}
stringData:
  {{- toYaml .Values.tls.data | nindent 2 }}
type: kubernetes.io/tls
{{- else }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.certManager.certificate }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.tls.secret }}
  issuerRef:
    name: {{ .Values.tls.certManager.issuer }}
    kind: Issuer
  dnsNames:
    - "{{ .Values.service.name }}.{{ .Values.namespace }}.svc"
    - "{{ .Values.service.name }}.{{ .Values.namespace }}"
    - "{{ .Values.service.name }}"
{{- end }}
