{{- if and .Values.tls.certManager.enabled .Values.tls.certManager.createIssuer }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.tls.certManager.issuer }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mirrord-license-server.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
