{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  {{- if .Values.server.annotations }}
  annotations:
    {{- include "mirrord-license-server.annotations" . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mirrord-license-server.labels" . | nindent 4 }}
{{ end }}
