apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirrord-license-server-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
