{{- if and .Values.database.auth .Values.database.auth.iamGcp (not .Values.sa.gcpSa) }}
  {{- fail ".database.auth.iamGcp was set as true but no value provided under .sa.gcpSa" }}
{{- end}}

apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.sa.gcpSa }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.sa.gcpSa }}
  {{- end }}
  labels:
    app: mirrord-license-server
    {{- include "mirrord-license-server.labels" . | nindent 4 }}
  name: {{ .Values.sa.name }}
  namespace: {{ .Values.namespace }}
