apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.sa.gcpSa }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.sa.gcpSa }}
  {{- end }}
  labels:
    app: mirrord-license-server
    {{- include "mirrord-license-server.labels" . | nindent 4 }}
  name: {{ .Values.sa.name }}
  namespace: {{ .Values.namespace }}
