apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.sa.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.sa.roleArn }}
  {{- end }}
  labels:
    app: mirrord-license-server
    {{- include "mirrord-license-server.labels" . | nindent 4 }}
  name: {{ .Values.sa.name }}
  namespace: {{ .Values.namespace }}
