apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: mirrord-license-server
    {{- include "mirrord-license-server.labels" . | nindent 4 }}
  name: {{ .Values.sa.name }}
  namespace: {{ .Values.namespace }}
